sources:
  - Tiny5.designspace
  - Tiny5Duo.designspace
  - Tiny5Mono.designspace
recipeProvider: googlefonts
recipe:
  # Modified recipe for decomposing components of Regular, Medium, and Bold static instances.

  # Tiny5 family build configuration.

  ../fonts/ttf/Tiny5-Regular.ttf:
  - source: Tiny5.designspace
  - glyphData: null
    instance_name: Tiny5-Regular
    operation: instantiateUfo
  - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildTTF
  - args: '--fail-ok '
    operation: autohint
  - args: ''
    operation: fix
  ../fonts/ttf/Tiny5-Medium.ttf:
  - source: Tiny5.designspace
  - glyphData: null
    instance_name: Tiny5-Medium
    operation: instantiateUfo
  - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildTTF
  - args: '--fail-ok '
    operation: autohint
  - args: ''
    operation: fix
  ../fonts/ttf/Tiny5-Bold.ttf:
  - source: Tiny5.designspace
  - glyphData: null
    instance_name: Tiny5-Bold
    operation: instantiateUfo
  - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildTTF
  - args: '--fail-ok '
    operation: autohint
  - args: ''
    operation: fix
  ../fonts/ttf/Tiny5-Italic.ttf:
  - source: Tiny5.designspace
  - glyphData: null
    instance_name: Tiny5-Italic
    operation: instantiateUfo
  - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildTTF
  - args: '--fail-ok '
    operation: autohint
  - args: ''
    operation: fix
  ../fonts/ttf/Tiny5-BoldItalic.ttf:
  - source: Tiny5.designspace
  - glyphData: null
    instance_name: Tiny5-BoldItalic
    operation: instantiateUfo
  - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildTTF
  - args: '--fail-ok '
    operation: autohint
  - args: ''
    operation: fix

  ../fonts/webfonts/Tiny5-Regular.woff2:
  - source: Tiny5.designspace
  - glyphData: null
    instance_name: Tiny5-Regular
    operation: instantiateUfo
  - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildTTF
  - args: '--fail-ok '
    operation: autohint
  - args: ''
    operation: fix
  - operation: compress
  ../fonts/webfonts/Tiny5-Medium.woff2:
  - source: Tiny5.designspace
  - glyphData: null
    instance_name: Tiny5-Medium
    operation: instantiateUfo
  - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildTTF
  - args: '--fail-ok '
    operation: autohint
  - args: ''
    operation: fix
  - operation: compress
  ../fonts/webfonts/Tiny5-Bold.woff2:
  - source: Tiny5.designspace
  - glyphData: null
    instance_name: Tiny5-Bold
    operation: instantiateUfo
  - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildTTF
  - args: '--fail-ok '
    operation: autohint
  - args: ''
    operation: fix
  - operation: compress
  ../fonts/webfonts/Tiny5-Italic.woff2:
  - source: Tiny5.designspace
  - glyphData: null
    instance_name: Tiny5-Italic
    operation: instantiateUfo
  - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildTTF
  - args: '--fail-ok '
    operation: autohint
  - args: ''
    operation: fix
  - operation: compress
  ../fonts/webfonts/Tiny5-BoldItalic.woff2:
  - source: Tiny5.designspace
  - glyphData: null
    instance_name: Tiny5-BoldItalic
    operation: instantiateUfo
  - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildTTF
  - args: '--fail-ok '
    operation: autohint
  - args: ''
    operation: fix
  - operation: compress

  # Tiny5 Duo family build configuration.

  ../fonts/ttf/Tiny5Duo-Regular.ttf:
  - source: Tiny5Duo.designspace
  - glyphData: null
    instance_name: Tiny5Duo-Regular
    operation: instantiateUfo
  - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildTTF
  - args: '--fail-ok '
    operation: autohint
  - args: ''
    operation: fix
  ../fonts/ttf/Tiny5Duo-Medium.ttf:
  - source: Tiny5Duo.designspace
  - glyphData: null
    instance_name: Tiny5Duo-Medium
    operation: instantiateUfo
  - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildTTF
  - args: '--fail-ok '
    operation: autohint
  - args: ''
    operation: fix
  ../fonts/ttf/Tiny5Duo-Bold.ttf:
  - source: Tiny5Duo.designspace
  - glyphData: null
    instance_name: Tiny5Duo-Bold
    operation: instantiateUfo
  - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildTTF
  - args: '--fail-ok '
    operation: autohint
  - args: ''
    operation: fix
  ../fonts/ttf/Tiny5Duo-Italic.ttf:
  - source: Tiny5Duo.designspace
  - glyphData: null
    instance_name: Tiny5Duo-Italic
    operation: instantiateUfo
  - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildTTF
  - args: '--fail-ok '
    operation: autohint
  - args: ''
    operation: fix
  ../fonts/ttf/Tiny5Duo-BoldItalic.ttf:
  - source: Tiny5Duo.designspace
  - glyphData: null
    instance_name: Tiny5Duo-BoldItalic
    operation: instantiateUfo
  - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildTTF
  - args: '--fail-ok '
    operation: autohint
  - args: ''
    operation: fix

  ../fonts/webfonts/Tiny5Duo-Regular.woff2:
  - source: Tiny5Duo.designspace
  - glyphData: null
    instance_name: Tiny5Duo-Regular
    operation: instantiateUfo
  - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildTTF
  - args: '--fail-ok '
    operation: autohint
  - args: ''
    operation: fix
  - operation: compress
  ../fonts/webfonts/Tiny5Duo-Medium.woff2:
  - source: Tiny5Duo.designspace
  - glyphData: null
    instance_name: Tiny5Duo-Medium
    operation: instantiateUfo
  - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildTTF
  - args: '--fail-ok '
    operation: autohint
  - args: ''
    operation: fix
  - operation: compress
  ../fonts/webfonts/Tiny5Duo-Bold.woff2:
  - source: Tiny5Duo.designspace
  - glyphData: null
    instance_name: Tiny5Duo-Bold
    operation: instantiateUfo
  - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildTTF
  - args: '--fail-ok '
    operation: autohint
  - args: ''
    operation: fix
  - operation: compress
  ../fonts/webfonts/Tiny5Duo-Italic.woff2:
  - source: Tiny5Duo.designspace
  - glyphData: null
    instance_name: Tiny5Duo-Italic
    operation: instantiateUfo
  - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildTTF
  - args: '--fail-ok '
    operation: autohint
  - args: ''
    operation: fix
  - operation: compress
  ../fonts/webfonts/Tiny5Duo-BoldItalic.woff2:
  - source: Tiny5Duo.designspace
  - glyphData: null
    instance_name: Tiny5Duo-BoldItalic
    operation: instantiateUfo
  - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildTTF
  - args: '--fail-ok '
    operation: autohint
  - args: ''
    operation: fix
  - operation: compress

#   # Tiny5 Mono family build configuration.

#   ../fonts/ttf/Tiny5Mono-Regular.ttf:
#   - source: Tiny5Mono.designspace
#   - glyphData: null
#     instance_name: Tiny5Mono-Regular
#     operation: instantiateUfo
#   - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
#     operation: buildTTF
#   - args: '--fail-ok '
#     operation: autohint
#   - args: ''
#     operation: fix
#   ../fonts/ttf/Tiny5Mono-Medium.ttf:
#   - source: Tiny5Mono.designspace
#   - glyphData: null
#     instance_name: Tiny5Mono-Medium
#     operation: instantiateUfo
#   - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
#     operation: buildTTF
#   - args: '--fail-ok '
#     operation: autohint
#   - args: ''
#     operation: fix
#   ../fonts/ttf/Tiny5Mono-Bold.ttf:
#   - source: Tiny5Mono.designspace
#   - glyphData: null
#     instance_name: Tiny5Mono-Bold
#     operation: instantiateUfo
#   - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
#     operation: buildTTF
#   - args: '--fail-ok '
#     operation: autohint
#   - args: ''
#     operation: fix
#   ../fonts/ttf/Tiny5Mono-Italic.ttf:
#   - source: Tiny5Mono.designspace
#   - glyphData: null
#     instance_name: Tiny5Mono-Italic
#     operation: instantiateUfo
#   - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
#     operation: buildTTF
#   - args: '--fail-ok '
#     operation: autohint
#   - args: ''
#     operation: fix
#   ../fonts/ttf/Tiny5Mono-BoldItalic.ttf:
#   - source: Tiny5Mono.designspace
#   - glyphData: null
#     instance_name: Tiny5Mono-BoldItalic
#     operation: instantiateUfo
#   - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
#     operation: buildTTF
#   - args: '--fail-ok '
#     operation: autohint
#   - args: ''
#     operation: fix

#   ../fonts/webfonts/Tiny5Mono-Regular.woff2:
#   - source: Tiny5Mono.designspace
#   - glyphData: null
#     instance_name: Tiny5Mono-Regular
#     operation: instantiateUfo
#   - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
#     operation: buildTTF
#   - args: '--fail-ok '
#     operation: autohint
#   - args: ''
#     operation: fix
#   - operation: compress
#   ../fonts/webfonts/Tiny5Mono-Medium.woff2:
#   - source: Tiny5Mono.designspace
#   - glyphData: null
#     instance_name: Tiny5Mono-Medium
#     operation: instantiateUfo
#   - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
#     operation: buildTTF
#   - args: '--fail-ok '
#     operation: autohint
#   - args: ''
#     operation: fix
#   - operation: compress
#   ../fonts/webfonts/Tiny5Mono-Bold.woff2:
#   - source: Tiny5Mono.designspace
#   - glyphData: null
#     instance_name: Tiny5Mono-Bold
#     operation: instantiateUfo
#   - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
#     operation: buildTTF
#   - args: '--fail-ok '
#     operation: autohint
#   - args: ''
#     operation: fix
#   - operation: compress
#   ../fonts/webfonts/Tiny5Mono-Italic.woff2:
#   - source: Tiny5Mono.designspace
#   - glyphData: null
#     instance_name: Tiny5Mono-Italic
#     operation: instantiateUfo
#   - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
#     operation: buildTTF
#   - args: '--fail-ok '
#     operation: autohint
#   - args: ''
#     operation: fix
#   - operation: compress
#   ../fonts/webfonts/Tiny5Mono-BoldItalic.woff2:
#   - source: Tiny5Mono.designspace
#   - glyphData: null
#     instance_name: Tiny5Mono-BoldItalic
#     operation: instantiateUfo
#   - args: --filter DecomposeComponentsFilter --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
#     operation: buildTTF
#   - args: '--fail-ok '
#     operation: autohint
#   - args: ''
#     operation: fix
#   - operation: compress
