familyName: Tiny5
sources:
  - tiny5-Regular.sfd
recipe:
  ../fonts/ttf/tiny5-Regular.ttf:
  - source: tiny5-Regular.sfd
  - operation: exec
    exe: babelfont
    args: $in tiny5-Regular.ufo
  - source: tiny5-Regular.ufo
  - operation: buildTTF
    args: --filter '...' --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
  - operation: exec
    exe: fonttools
    args: feaLib features.fea $in -o $out -t GSUB GDEF
  - operation: autohint
  - operation: fix
    args: --include-source-fixes
  - operation: rename
    args: --just-family
    name: Tiny5
  ../fonts/otf/tiny5-Regular.otf:
  - source: tiny5-Regular.sfd
  - operation: exec
    exe: babelfont
    args: $in tiny5-Regular.ufo
  - source: tiny5-Regular.ufo
  - operation: buildOTF
  - operation: exec
    exe: fonttools
    args: feaLib features.fea $in -o $out -t GSUB GDEF
